### ISSUE TITLE
Bufler installation from MELPA fails with compilation error

### ISSUE THREAD

**Issue by ivanruski** [alphapapa/bufler.el#78] opened 2021-10-30 18:28 UTC
Hello, 

I am using Emacs 27.1 on OSX and when I try to install bufler from MELPA I get the following error:
```
Compiling file ~/.emacs.d/elpa/bufler-20210907.1145/bufler-workspace-tabs.el at Sat Oct 30 21:21:13 2021
bufler-workspace-tabs.el:70:34:Error: Recursive ‘require’ for feature ‘bufler-workspace’
```
Then when I try to turn on `bufler-mode` I get `Recursive load` error.

And if I remove the require on line 70 in `bufler-workspace-tabs.el` it works.
Is this the recommended approach or there might be a problem on might side ?

**Comment by alphapapa** [comment] 2022-04-04 11:32
Hello @ivanruski ,

Does this still happen?  Since you closed this issue without comment, I don't know if the problem is solved.

**Comment by joshbax189** [comment] 2022-05-02 07:58
Same problem:
```
Compiling internal form(s) at Mon May  2 19:44:06 2022
Leaving directory ‘/tmp/tmp.VMnweJqivA/elpa/bufler-20210907.1145’

Compiling file /tmp/tmp.VMnweJqivA/elpa/bufler-20210907.1145/bufler-group-tree.el at Mon May  2 19:44:06 2022
Entering directory ‘/tmp/tmp.VMnweJqivA/elpa/bufler-20210907.1145/’

Compiling file /tmp/tmp.VMnweJqivA/elpa/bufler-20210907.1145/bufler-workspace-tabs.el at Mon May  2 19:44:06 2022
bufler-workspace-tabs.el:70:34: Error: Recursive ‘require’ for feature ‘bufler-workspace’

Compiling file /tmp/tmp.VMnweJqivA/elpa/bufler-20210907.1145/bufler-workspace.el at Mon May  2 19:44:06 2022

Compiling file /tmp/tmp.VMnweJqivA/elpa/bufler-20210907.1145/bufler.el at Mon May  2 19:44:06 2022
bufler.el:769:42: Warning: Unused lexical argument ‘depth’
```
(PS reproduced using with-emacs.sh thanks!!)

On Arch/AUR emacs version:
```
local/emacs-git 28.0.50.145041-1
    GNU Emacs. Development master branch.
```
Not sure of the exact origin of the problem, but I could work around by replacing `eval-when-compile` [(bufler-workspace-tabs.el:39)](https://github.com/alphapapa/bufler.el/blob/a68e0eb2719c67ab8a3ad56c4036364061d06004/bufler-workspace-tabs.el#L39) with `cl-eval-when (compile)`. 

(I noticed that the [elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Eval-During-Compile.html) says `eval-when-compile` is like `cl-eval-when (compile eval)` and guessed the fix was closer to the intended use?)

**Comment by ivanruski** [comment] 2022-05-02 15:08
Hi @alphapapa I just tried installing bufler again with the following init.el:
```elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
```

and I got the same error:
```
Compiling file /Users/ivanruski/.emacs.d/elpa/bufler-20210907.1145/bufler-group-tree.el at Mon May  2 18:06:21 2022
Entering directory ‘/Users/ivanruski/.emacs.d/elpa/bufler-20210907.1145/’

Compiling file /Users/ivanruski/.emacs.d/elpa/bufler-20210907.1145/bufler-workspace-tabs.el at Mon May  2 18:06:21 2022
bufler-workspace-tabs.el:70:34:Error: Recursive ‘require’ for feature ‘bufler-workspace’

Compiling file /Users/ivanruski/.emacs.d/elpa/bufler-20210907.1145/bufler-workspace.el at Mon May  2 18:06:22 2022

Compiling file /Users/ivanruski/.emacs.d/elpa/bufler-20210907.1145/bufler.el at Mon May  2 18:06:22 2022
bufler.el:769:42:Warning: Unused lexical argument ‘depth’
```
I am using GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12

**Comment by jjnilton** [comment] 2022-05-02 23:07
Having the same issue when installing from MELPA on GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-03-27, modified by Debian.

**Comment by NicholasBHubbard** [comment] 2022-06-14 21:00
Same issue when installing from MELPA on GNU Emacs 27.2 (build 1, x86_64-slackware-linux-gnu, GTK+ Version 3.24.27) of 2021-03-25

**Comment by alphapapa** [comment] 2022-08-05 21:36
This was likely fixed by https://github.com/alphapapa/bufler.el/commit/31173ff3ff4f7c01c3d9deea7b13bb22e33cc8dd.  See also #80.  Please let me know if the problem still occurs.

**Comment by NicholasBHubbard** [comment] 2022-08-05 22:05
Fixed it for me

**Comment by alphapapa** [comment] 2022-08-06 01:16
Thanks.  Closing.

**Closed by alphapapa** 2022-08-06 01:16 UTC
Labels: bug, waiting
