### ISSUE TITLE
Error while loading autoloads

### ISSUE THREAD

**Issue by akirak** [alphapapa/bufler.el#80] opened 2022-01-02 14:24 UTC
Hello, I encountered the following error when I started Emacs with bufler:

> load-with-code-conversion: Symbol’s function definition is void: cl-eval-when

This happens even when I don't turn on `bufler-mode`. It seems to be from an autoload, which is generated from the following location:

https://github.com/alphapapa/bufler.el/blob/a68e0eb2719c67ab8a3ad56c4036364061d06004/bufler-workspace.el#L247-L250

`cl-eval-when` is included in `cl-macs.el`, so cl-macs must be loaded inside the autoloads before the expansion of `cl-eval-when`. The following worked:

```emacs-lisp
;;;###autoload
(require 'cl-macs)
```

**Comment by alphapapa** [comment] 2022-03-01 10:18
Thanks, Akira.  What version of Emacs are you using?

**Comment by akirak** [comment] 2022-03-01 10:41
> Thanks, Akira. What version of Emacs are you using?

I think I used either Emacs 28.0.90 or 29.0.50. Maybe native compilation was enabled. That is an unstable version and can produce false negatives, so I am not sure if the issue still remains. I have to check it later.

**Comment by Tass0sm** [comment] 2022-03-27 18:27
I also ran into this issue when writing a bufler package for GNU Guix

**Comment by akirak** [comment] 2022-03-27 18:52
I was  using Emacs 29.0.50.

**Comment by alphapapa** [comment] 2022-04-04 11:38
I don't understand why this is happening.  I just tested installing Bufler into a clean Emacs configuration from MELPA, and then ran `M-x bufler`, and there were no errors.  I also tried restarting Emacs after installing the package (since sometimes errors like this can appear only after restarting Emacs after installing a package, because `package-install` loads the code when compiling it), and there were also no errors.  I tried using both Emacs 26.3 and Emacs 28.0.92, and both worked without error, so I'm unable to reproduce the problem.

**Comment by Tass0sm** [comment] 2022-04-06 22:31
I only received a warning when compiling bufler. I later removed the "build" phase in the package definition for another reason. The uncompiled bufler worked without any issues in my emacs-28.0.50.

The Guix build system uses a clean emacs 27.2 for compiling. Here's the exact command it uses.

`/gnu/store/mbysw8z6gwrz4plvg1622aigjwlw81bm-emacs-minimal-27.2/bin/emacs --quick --batch --eval="(eval '(progn (setq byte-compile-debug t) (byte-recompile-directory (file-name-as-directory \"/gnu/store/c2x11n1mvvrz5a8p626faypfrhxmzzxq-emacs-bufler-20210907.1145/share/emacs/site-lisp/bufler-20210907.1145\") 0 1)) t)"`

Here are the warning messages I get when it tries to compile the autoloads file.

`Compiling /gnu/store/c2x11n1mvvrz5a8p626faypfrhxmzzxq-emacs-bufler-20210907.1145/share/emacs/site-lisp/bufler-20210907.1145/bufler-autoloads.el...

In toplevel form:
bufler-autoloads.el:109:16:Warning: load called with 0 arguments, but requires
    1-5

In end of data:
bufler-autoloads.el:130:1:Warning: the function ‘cl-eval-when’ is not known to
    be defined.`

I'll also include an error message I got when compiling bufler-workspace-tabs.el, but I'm pretty sure its a problem with my package definition.

`Compiling /gnu/store/c2x11n1mvvrz5a8p626faypfrhxmzzxq-emacs-bufler-20210907.1145/share/emacs/site-lisp/bufler-20210907.1145/bufler-workspace-tabs.el...
Cannot open load file: No such file or directory, magit-section`

**Comment by chasecaleb** [comment] 2022-05-10 19:56
I also get this on Emacs 28.1. I wonder if this compile-time warning is a hint as to why?

```
bufler> Compiling: /build/source/bufler-workspace-tabs.el
bufler> Warning: Eager macro-expansion skipped due to cycle:
bufler>   … => (load "bufler-workspace-tabs.el") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load "bufler-workspace.el") => (load "bufler-workspace-tabs.el")
bufler> Eager macro-expansion failure: (error "Recursive `require' for feature `bufler-workspace'")
```

**Comment by ReggieMarr** [comment] 2022-07-26 13:16
I can confirm I also get the same kind of issue with emacs 29.0.50 and doom.
When running doom upgrade/sync/purge I get the following:
```
(error "Eager macro-expansion failure: %S" (error "Eager macro-expansion skipped due to cycle:\n  … => (load \"bufler-workspace-tabs.el\") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) ...
      (internal-macroexpand-for-load (eval-when-compile (when (version< emacs-version "27.1") (defvar tab-bar-tabs-function) (defvar tab-bar-close-button) (defvar tab-bar-close-button-show) (defvar tab-bar-s...
      (load-with-code-conversion "/home/reggiemarr/.emacs.d/.local/straight/build-29.0.50/bufler/bufler-workspace-tabs.el" "/home/reggiemarr/.emacs.d/.local/straight/build-29.0.50/bufler/bufler-workspace-tab...
      (require bufler-workspace-tabs)
      (byte-code "\300\301\302\303#\203\f\300\304!\210\305\306\307\"\210\305\310\311\"\210\305\312\313\"\210\305\314\315\"\210\305\316\317\"\207" [require tab-bar nil t bufler-workspace-tabs register-defin...
      (load "/home/reggiemarr/.emacs.d/.local/autoloads.29.0.50" nil nomessage)
      (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) ((debug file-missing) (if (locate-file doom-autoloads-file load-path) (signal 'doom-autoload-error e) (signal 'd...
      (load-with-code-conversion "/home/reggiemarr/.emacs.d/core/core-start.el" "/home/reggiemarr/.emacs.d/core/core-start.el" nil t)
      (require core-start)
      (let ((noninteractive nil) kill-emacs-query-functions kill-emacs-hook) (defvar doom-reloading-p nil) (require 'core-start) (doom-initialize-packages))
      (let ((doom-print-indent (+ (if t doom-print-indent-increment 0) doom-print-indent))) (let ((noninteractive nil) kill-emacs-query-functions kill-emacs-hook) (defvar doom-reloading-p nil) (require 'core...
      (condition-case ex (let ((doom-print-indent (+ (if t doom-print-indent-increment 0) doom-print-indent))) (let ((noninteractive nil) kill-emacs-query-functions kill-emacs-hook) (defvar doom-reloading-p ...
    ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220726090453.9026.error

```

**Comment by alphapapa** [comment] 2022-07-26 17:01
Thanks to all of you for reporting these problems.  It's not easy to cleanly support multiple Emacs versions with differing feature sets, especially when being built and installed by different methods.  I hope that commit 31173ff will resolve the compilation warnings and still behave as correctly as possible on versions 26.3 through 28.1.  Please let me know if the problems seem to be solved for you.

**Comment by ReggieMarr** [comment] 2022-07-26 18:06
@alphapapa I just did a ```doom upgrade && doom sync`` which pulled in your latest. Works for me now.

**Comment by Tass0sm** [comment] 2022-07-26 19:20
Worked for me too. Also finished the Guix package for bufler. Thanks!

**Comment by alphapapa** [comment] 2022-07-27 12:39
@ReggieMarr Thanks.

@Tass0sm Great, thanks for doing that.

I'll close this as solved.

**Closed by alphapapa** 2022-07-27 12:39 UTC
Labels: bug
